# Generated by Django 2.2 on 2019-06-08 15:16

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingAreas',
            fields=[
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=20, null=True)),
                ('area_image', models.ImageField(height_field='height', upload_to=master.models.user_directory_path, width_field='width')),
                ('row_count', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SlotDims',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_left', models.IntegerField()),
                ('y_left', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('row', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='master.ParkingAreas')),
            ],
        ),
    ]
