# Generated by Django 2.2 on 2019-05-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingAreas',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=20)),
                ('area_image', models.ImageField(upload_to='areas/')),
                ('row_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotDims',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_left', models.IntegerField()),
                ('y_left', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('row', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ParkingAreas')),
            ],
        ),
    ]
