# Generated by Django 2.2 on 2019-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdims',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
