# Generated by Django 2.2 on 2019-05-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingareas',
            name='area_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
