# Generated by Django 2.2 on 2019-06-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_slotdims_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderDims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_left', models.IntegerField()),
                ('y_left', models.IntegerField()),
                ('slot_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='render_dims', to='master.SlotDims')),
            ],
        ),
    ]
