# Generated by Django 2.2 on 2019-05-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20190508_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingareas',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingareas',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
