# Generated by Django 2.2 on 2019-06-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_renderdims'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingareas',
            name='column_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='slotdims',
            name='column',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
