# Generated by Django 2.2 on 2019-05-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20190508_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingareas',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parkingareas',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
