# Generated by Django 2.2 on 2019-05-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20190508_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdims',
            name='area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='master.ParkingAreas'),
        ),
    ]
