# Generated by Django 2.2 on 2019-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20190525_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingareas',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
