# Generated by Django 2.2 on 2019-05-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('occupied', models.BooleanField()),
                ('cnn_timestamp', models.DateTimeField()),
                ('cnnflag', models.BooleanField(default=False)),
                ('confidence', models.IntegerField(default=0)),
            ],
        ),
    ]
