# Generated by Django 2.2 on 2019-05-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0002_slotscache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotscache',
            name='slot_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_cache', to='gridapp.Slots'),
        ),
    ]
