# Generated by Django 2.2 on 2019-05-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20190505_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='slot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gridapp.Slots'),
        ),
    ]
